### ISSUE TITLE
Shell

### ISSUE THREAD

**Issue by reinauer** [EmberHeavyIndustries/AMI-RGB2VGAPLUS#1]
Hi,

is there any chance that you can design a shell for this? Unfortunately the sleak looking ones like https://www.thingiverse.com/thing:4692954 won't fit. I was going to give it a shot but without the KiCAD files or an STL of the populated board it is a lot of guess work to produce something decent looking.

**Comment by EmberHeavyIndustries** [comment]
Hi there,
honestly, I doubt I have enough free time to follow all funny projects I would have in mind to follow .. this one comprised ;)
Further, I am an absolute n00b at 3D modelling; I can do that, but with lots of (probably unneeded) efforts from my side.

What I can do is to share the PCB's 3D object files to allow skilled users to easily (for their skills) design a shell.
Find the "OBJ_PCB_RGB2VGA_V2_2024-08-27.zip" file in Hardware folder, it should be enough (please check it fits the actual pcb)
